version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.20
    container_name: easystore-consul
    ports:
      - "8500:8500"   # HTTP API & UI
      - "8600:8600/udp" # DNS
    command: agent -dev -ui -client=0.0.0.0 -bind=0.0.0.0
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - easystore-network
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: easystoredb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=easystore_product
    volumes:
      - ./eazystore-data:/var/lib/mysql
      - ./db/init/product-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - easystore-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  contact-db:
    image: mysql:8.0
    container_name: easystore-contact-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=easystore_contact
    volumes:
      - ./eazystore-contact-data:/var/lib/mysql
      - ./db/init/contact-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - easystore-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  identity-db:
    image: mysql:8.0
    container_name: easystore-identity-db
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=easystore_identity
    volumes:
      - ./eazystore-identity-data:/var/lib/mysql
      - ./db/init/identity-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - easystore-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7.0-alpine
    container_name: easystore-redis
    ports:
      - "6379:6379"
    networks:
      - easystore-network

networks:
  easystore-network:
    driver: bridge
