spring:
  application:
    name: api-gateway
  threads:
    virtual:
      enabled: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${server.port}
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/api/v1/contacts/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/v1/ai/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

server:
  port: 8080
